### ISSUE TITLE
Wiki Home Page

### ISSUE THREAD

**Issue by PedroKim** [muharremb/mebook#1]
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

## Comments
- Have a placeholder for live link

**Comment by muharremb** [comment]
Mebook Live link added to Home Wiki Page.
