### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by PedroKim** [muharremb/mebook#5]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
- [x] `PostForm` should be included in newsfeed and profile pages. We don't need additional routes for new and edit.

**Comment by muharremb** [comment]
I removed additional post routes for new and edit. I include PostForm to feed and profile pages.

**Comment by PedroKim** [comment]
- [ ] Please make changes on wiki page as well.
